/**
 * Sirius Star Lab — CAD Auto-Generation
 *
 * When a project is sent to New Dimensions, this module:
 *   1. Uses GPT-4o to generate a professional SVG engineering drawing
 *   2. Uploads the SVG to object storage
 *   3. POSTs the drawing to New Dimensions (so it appears in the ND UI)
 *   4. Imports the file into Star Lab's cad_files table
 *   5. Marks the cad_jobs record as "complete"
 *   6. Calls onCadFileAttached() → project moves to "launch-ready"
 */

import { eq, desc } from "drizzle-orm";
import { db, cadFiles, cadJobs, labProjects } from "@workspace/db";
import { openai } from "@workspace/integrations-openai-ai-server";
import { ObjectStorageService } from "./objectStorage.js";

const storage = new ObjectStorageService();

const ND_BASE_URL = () =>
  (process.env.NEWDIMENSIONS_BASE_URL || "https://new-dimension-cad.replit.app").replace(/\/$/, "");
const ND_API_KEY = () => process.env.NEWDIMENSIONS_API_KEY || "";

export async function generateAndPostCadDrawing(
  projectId: number,
  ndProjectId: string,
  projectName: string,
  description: string,
): Promise<void> {
  console.log(`[CAD Auto-Gen] ⚙ Starting for "${projectName}" (ND #${ndProjectId})`);

  try {
    const today = new Date().toLocaleDateString("en-GB");
    const drgNo = `SL-${projectId.toString().padStart(4, "0")}`;

    // 1. Generate SVG via GPT-4o
    const completion = await openai.chat.completions.create({
      model: "openai/gpt-4o",
      messages: [
        {
          role: "user",
          content: `You are an expert mechanical/engineering draughtsman. Generate a professional SVG technical drawing for the following component.

PROJECT: ${projectName}

SPECIFICATION:
${description}

OUTPUT RULES — CRITICAL:
- Output ONLY raw SVG. No markdown, no code fences, no explanation. Start with <svg and end with </svg>.
- viewBox="0 0 1200 900" width="1200" height="900"
- White background rectangle filling the whole canvas
- Black lines and text only (stroke="#000" fill="none" for geometry, fill="#000" for text)
- Show at minimum: front orthographic view + side/section view, clearly labelled
- Include dimension lines with leader arrows and measurement values (inferred from spec)
- Include a professional title block in the bottom-right corner containing:
    Part Name: ${projectName}
    Scale: 1:1   Date: ${today}   Drg No: ${drgNo}
- All text: font-family="Arial,sans-serif"
- The result must look like a real BS/ISO engineering drawing, not a schematic`,
        },
      ],
      max_tokens: 4000,
    });

    let svgContent = completion.choices[0]?.message?.content?.trim() ?? "";
    const svgMatch = svgContent.match(/<svg[\s\S]*<\/svg>/i);
    if (svgMatch) svgContent = svgMatch[0];
    if (!svgContent.toLowerCase().startsWith("<svg")) {
      throw new Error("AI did not return valid SVG — response: " + svgContent.slice(0, 200));
    }

    // 2. Upload SVG to object storage
    const svgBuffer = Buffer.from(svgContent, "utf-8");
    const uploadURL = await storage.getObjectEntityUploadURL();
    const objectPath = storage.normalizeObjectEntityPath(uploadURL);
    await fetch(uploadURL, {
      method: "PUT",
      headers: { "Content-Type": "image/svg+xml" },
      body: svgBuffer,
    });

    // Signed URL valid for 2 hours — enough time for ND to serve it back to us
    const signedFileUrl = await storage.getObjectEntityDownloadURL(objectPath, 7200);

    // 3. POST drawing to New Dimensions so it appears in the ND UI
    const ndBase = ND_BASE_URL();
    const apiKey = ND_API_KEY();
    const ndHeaders: Record<string, string> = { "Content-Type": "application/json" };
    if (apiKey) {
      ndHeaders["Authorization"] = `Bearer ${apiKey}`;
      ndHeaders["X-API-Key"] = apiKey;
    }

    const drawRes = await fetch(`${ndBase}/api/projects/${ndProjectId}/drawings`, {
      method: "POST",
      headers: ndHeaders,
      body: JSON.stringify({
        name: `${projectName} — Technical Drawing`,
        fileUrl: signedFileUrl,
        fileType: "svg",
        description: "Auto-generated by Sirius Star Lab AI",
      }),
    });

    if (!drawRes.ok) {
      const errText = await drawRes.text();
      console.warn(`[CAD Auto-Gen] ⚠ New Dimensions rejected drawing POST: ${drawRes.status} ${errText}`);
    } else {
      const ndDrawing = (await drawRes.json()) as any;
      console.log(`[CAD Auto-Gen] ✅ Drawing posted to New Dimensions (drawing #${ndDrawing.id})`);
    }

    // 4. Import the file into Star Lab's cad_files table
    const safeFileName = `${projectName.replace(/[^a-z0-9_\-]/gi, "_")}_drawing.svg`;
    await db.insert(cadFiles).values({
      projectId,
      fileName: safeFileName,
      fileSize: svgBuffer.length,
      fileType: "image/svg+xml",
      objectPath,
      description: "Auto-generated CAD drawing (Sirius AI)",
    });

    // 5. Mark cad_job complete
    const [job] = await db
      .select({ id: cadJobs.id, status: cadJobs.status })
      .from(cadJobs)
      .where(eq(cadJobs.projectId, projectId))
      .orderBy(desc(cadJobs.createdAt))
      .limit(1);

    if (job && job.status === "pending") {
      await db
        .update(cadJobs)
        .set({ status: "complete", completedAt: new Date() })
        .where(eq(cadJobs.id, job.id));
    }

    // 6. Move project to "launch-ready" if it was cad-pending
    const [proj] = await db
      .select({ id: labProjects.id, launchStatus: labProjects.launchStatus, name: labProjects.name })
      .from(labProjects)
      .where(eq(labProjects.id, projectId))
      .limit(1);
    if (proj?.launchStatus === "cad-pending") {
      await db
        .update(labProjects)
        .set({ launchStatus: "launch-ready", updatedAt: new Date() })
        .where(eq(labProjects.id, projectId));
      console.log(`[CAD Auto-Gen] ✅ "${proj.name}" → LAUNCH READY`);
    }

    console.log(`[CAD Auto-Gen] ✅ Complete — "${projectName}" drawing imported into Star Lab`);
  } catch (err: any) {
    console.error(`[CAD Auto-Gen] ❌ Failed for "${projectName}":`, err.message);
    try {
      const [job] = await db
        .select({ id: cadJobs.id, status: cadJobs.status })
        .from(cadJobs)
        .where(eq(cadJobs.projectId, projectId))
        .orderBy(desc(cadJobs.createdAt))
        .limit(1);
      if (job && job.status === "pending") {
        await db
          .update(cadJobs)
          .set({
            status: "error",
            errorMessage: `Auto-gen failed: ${err.message}`,
            completedAt: new Date(),
          })
          .where(eq(cadJobs.id, job.id));
      }
    } catch {
      /* ignore cleanup errors */
    }
  }
}
