import { Router, type IRouter } from "express";
import healthRouter from "./health";
import intelligenceRouter from "./intelligence";
import openaiRouter from "./openai";
import subscriptionRouter from "./subscription";
import stripeRouter from "./stripe";
import labRouter from "./lab";
import labAppBuilderRouter from "./lab-app-builder";
import intelligenceFeedRouter from "./intelligence-feed";
import outreachRouter from "./outreach";
import learnRouter from "./learn";
import revenueRouter from "./revenue";
import agencyRouter from "./agency";
import publicRouter from "./public";
import fitstackRouter from "./fitstack";
import dreamLabRouter from "./dream-lab";
import paymentRouter from "./payment";
import intelligenceProxyRouter from "./intelligence-proxy.js";
import selfModifyRouter from "./self-modify.js";
import authRouter from "./auth.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(publicRouter);
router.use(healthRouter);
router.use(openaiRouter);
router.use(intelligenceRouter);
router.use(subscriptionRouter);
router.use(stripeRouter);
router.use(labRouter);
router.use(labAppBuilderRouter);
router.use(intelligenceFeedRouter);
router.use(outreachRouter);
router.use(learnRouter);
router.use(revenueRouter);
router.use(agencyRouter);
router.use("/fitstack", fitstackRouter);
router.use(dreamLabRouter);
router.use(paymentRouter);
router.use(intelligenceProxyRouter);
router.use("/lab", selfModifyRouter);

export default router;
