// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sirius-landing/LandingPage.tsx": () => import("../components/mockups/sirius-landing/LandingPage.tsx"),
  "./components/mockups/sirius-landing/MinimalLanding.tsx": () => import("../components/mockups/sirius-landing/MinimalLanding.tsx"),
  "./components/mockups/sirius-landing/UpgradeModal.tsx": () => import("../components/mockups/sirius-landing/UpgradeModal.tsx")
};
