import { pgTable, serial, text, timestamp, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const labProjects = pgTable("lab_projects", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  industry: text("industry").notNull().default("General"),

  // Phase: "design" | "production" | "complete"
  phase: text("phase").notNull().default("design"),
  status: text("status").notNull().default("active"),

  // Manufacturing / engineering process — e.g. "CNC Milling 3-Axis", "Injection Moulding"
  // Empty string = not applicable (digital/software project)
  manufacturingProcess: text("manufacturing_process").default(""),

  // Design phase fields
  brief: text("brief").default(""),
  research: text("research").default(""),
  specs: text("specs").default(""),
  code: text("code").default(""),
  drawingNotes: text("drawing_notes").default(""),
  cadUrl: text("cad_url").default(""),
  materials: text("materials").default(""),

  // Production phase fields
  workflows: text("workflows").default(""),
  industryProblem: text("industry_problem").default(""),
  uses: text("uses").default(""),

  // Complete phase fields
  brochure: text("brochure").default(""),
  pitch: text("pitch").default(""),
  costToBuild: text("cost_to_build").default(""),
  profitMargin: text("profit_margin").default(""),

  // Market & commercialisation fields
  businessCase: text("business_case").default(""),
  goToMarket: text("go_to_market").default(""),

  // Renders — JSON array of { url: string, label: string, type: "2d"|"3d"|"photo" }
  renders: text("renders").default("[]"),

  // Investment rule — extracted from businessCase/costToBuild, used for auto-archiving
  investmentRequired: integer("investment_required"),  // GBP, null = not yet assessed
  investmentAssessedAt: timestamp("investment_assessed_at", { withTimezone: true }),

  // Autonomous lab — set when project was auto-created by the daily scanner
  autoCreated: text("auto_created").default(""),   // "" | "auto"
  autoScanId: text("auto_scan_id").default(""),

  // Approval workflow — auto-created projects start as "pending"
  approvalStatus: text("approval_status").default(""),  // "" | "pending" | "approved" | "rejected"

  // Launch / social media
  socialPosts: text("social_posts").default("{}"),   // JSON: { linkedin: "", twitter: "", instagram: "", facebook: "", pressRelease: "" }
  launchPlatforms: text("launch_platforms").default("[]"), // JSON: string[] of selected platform IDs
  launchStatus: text("launch_status").default(""),   // "" | "draft" | "approved" | "launched"

  // Funding analysis — auto-populated per project
  fundingAnalysis: text("funding_analysis").default(""),
  fundingStatus: text("funding_status").default(""),   // "" | "pending" | "complete" | "error"
  fundingAnalysedAt: timestamp("funding_analysed_at", { withTimezone: true }),

  // Funding applications — JSON: { [schemeKey]: { application: string, generatedAt: string } }
  fundingApplications: text("funding_applications").default("{}"),

  // AI Architecture sweep — daily autonomous analysis linking projects to app dev tools
  aiArchLinked: text("ai_arch_linked").default(""),   // "" | "pending" | "linked" | "not-applicable"
  aiArchInsights: text("ai_arch_insights").default(""),  // JSON: AiArchInsights
  aiArchSweepAt: timestamp("ai_arch_sweep_at", { withTimezone: true }),

  // Sales & Marketing Plan — generated by orchestrator
  // JSON: SalesPlan (see orchestrator.ts)
  salesPlan: text("sales_plan").default(""),
  salesPlanGeneratedAt: timestamp("sales_plan_generated_at", { withTimezone: true }),

  // Stripe payment link — generated when project goes live to market
  stripeProductId: text("stripe_product_id").default(""),    // Stripe Product ID (prod_...)
  stripePriceId: text("stripe_price_id").default(""),        // Stripe Price ID (price_...)
  stripePaymentLink: text("stripe_payment_link").default(""), // Reusable Stripe payment link URL
  sellPrice: integer("sell_price"),                          // Price in pence (GBP), null = not set
  sellPriceType: text("sell_price_type").default(""),        // "one_time" | "monthly" | "yearly"

  // Product Packaging — auto-generated when project completes
  landingPage: text("landing_page").default(""),   // Complete standalone HTML landing page
  embedCode: text("embed_code").default(""),       // Compact HTML embed widget snippet

  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const insertLabProjectSchema = createInsertSchema(labProjects).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type LabProject = typeof labProjects.$inferSelect;
export type InsertLabProject = z.infer<typeof insertLabProjectSchema>;
